// Code generated by flagxgen; DO NOT EDIT.

package flagx

import (
	"strconv"
	"time"
)

func stringCodec[T ~string]() Codec[T] {
	return Codec[T]{
		Parse: func(value string) (T, error) {
			return T(value), nil
		},
		Format: func(value T) string {
			return string(value)
		},
		Type: "string",
	}
}

func boolCodec[T ~bool]() Codec[T] {
	return Codec[T]{
		Parse: func(value string) (T, error) {
			parsed, err := strconv.ParseBool(value)
			return T(parsed), err
		},
		Format: func(value T) string {
			return strconv.FormatBool(bool(value))
		},
		Type:   "bool",
		IsBool: true,
	}
}

func signedIntegerCodec[T signedInteger](bitSize int, typeName string) Codec[T] {
	return Codec[T]{
		Parse: func(value string) (T, error) {
			parsed, err := strconv.ParseInt(value, 0, bitSize)
			return T(parsed), err
		},
		Format: func(value T) string {
			return strconv.FormatInt(int64(value), 10)
		},
		Type: typeName,
	}
}

func unsignedIntegerCodec[T unsignedInteger](bitSize int, typeName string) Codec[T] {
	return Codec[T]{
		Parse: func(value string) (T, error) {
			parsed, err := strconv.ParseUint(value, 0, bitSize)
			return T(parsed), err
		},
		Format: func(value T) string {
			return strconv.FormatUint(uint64(value), 10)
		},
		Type: typeName,
	}
}

func floatingPointCodec[T floatingPoint](bitSize int, typeName string) Codec[T] {
	return Codec[T]{
		Parse: func(value string) (T, error) {
			parsed, err := strconv.ParseFloat(value, bitSize)
			return T(parsed), err
		},
		Format: func(value T) string {
			return strconv.FormatFloat(float64(value), 'g', -1, bitSize)
		},
		Type: typeName,
	}
}

func durationCodec[T ~int64]() Codec[T] {
	return Codec[T]{
		Parse: func(value string) (T, error) {
			parsed, err := time.ParseDuration(value)
			return T(parsed), err
		},
		Format: func(value T) string {
			return time.Duration(value).String()
		},
		Type: "duration",
	}
}
