// Code generated by flagxgen; DO NOT EDIT.

package flagx

type signedInteger interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64
}

type unsignedInteger interface {
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64
}

type floatingPoint interface {
	~float32 | ~float64
}
