// Code generated by flagxgen; DO NOT EDIT.

package flagx

import (
	"github.com/spf13/pflag"
	"strconv"
)

func String[T ~string](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, stringCodec[T](), opts...)
}

func StringP[T ~string](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, stringCodec[T](), opts...)
}

func Bool[T ~bool](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, boolCodec[T](), opts...)
}

func BoolP[T ~bool](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, boolCodec[T](), opts...)
}

func Int[T ~int](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, signedIntegerCodec[T](strconv.IntSize, "int"), opts...)
}

func IntP[T ~int](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, signedIntegerCodec[T](strconv.IntSize, "int"), opts...)
}

func Int8[T ~int8](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, signedIntegerCodec[T](8, "int8"), opts...)
}

func Int8P[T ~int8](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, signedIntegerCodec[T](8, "int8"), opts...)
}

func Int16[T ~int16](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, signedIntegerCodec[T](16, "int16"), opts...)
}

func Int16P[T ~int16](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, signedIntegerCodec[T](16, "int16"), opts...)
}

func Int32[T ~int32](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, signedIntegerCodec[T](32, "int32"), opts...)
}

func Int32P[T ~int32](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, signedIntegerCodec[T](32, "int32"), opts...)
}

func Int64[T ~int64](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, signedIntegerCodec[T](64, "int64"), opts...)
}

func Int64P[T ~int64](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, signedIntegerCodec[T](64, "int64"), opts...)
}

func Uint[T ~uint](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, unsignedIntegerCodec[T](strconv.IntSize, "uint"), opts...)
}

func UintP[T ~uint](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, unsignedIntegerCodec[T](strconv.IntSize, "uint"), opts...)
}

func Uint8[T ~uint8](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, unsignedIntegerCodec[T](8, "uint8"), opts...)
}

func Uint8P[T ~uint8](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, unsignedIntegerCodec[T](8, "uint8"), opts...)
}

func Uint16[T ~uint16](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, unsignedIntegerCodec[T](16, "uint16"), opts...)
}

func Uint16P[T ~uint16](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, unsignedIntegerCodec[T](16, "uint16"), opts...)
}

func Uint32[T ~uint32](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, unsignedIntegerCodec[T](32, "uint32"), opts...)
}

func Uint32P[T ~uint32](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, unsignedIntegerCodec[T](32, "uint32"), opts...)
}

func Uint64[T ~uint64](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, unsignedIntegerCodec[T](64, "uint64"), opts...)
}

func Uint64P[T ~uint64](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, unsignedIntegerCodec[T](64, "uint64"), opts...)
}

func Float32[T ~float32](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, floatingPointCodec[T](32, "float32"), opts...)
}

func Float32P[T ~float32](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, floatingPointCodec[T](32, "float32"), opts...)
}

func Float64[T ~float64](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, floatingPointCodec[T](64, "float64"), opts...)
}

func Float64P[T ~float64](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, floatingPointCodec[T](64, "float64"), opts...)
}

func Duration[T ~int64](flagSet *pflag.FlagSet, name string, target *T, usage string, opts ...Option[T]) {
	Any(flagSet, name, target, usage, durationCodec[T](), opts...)
}

func DurationP[T ~int64](flagSet *pflag.FlagSet, name string, shorthand string, target *T, usage string, opts ...Option[T]) {
	AnyP(flagSet, name, shorthand, target, usage, durationCodec[T](), opts...)
}
