package main

import (
	"bytes"
	"fmt"
	"log"
	"slices"
	"strconv"
)

type generator struct {
	bytes.Buffer
}

const pflagImportPath = "github.com/spf13/pflag"

func (g *generator) l(args ...any) {
	_, err := fmt.Fprint(&g.Buffer, args...)
	if err != nil {
		log.Fatal(err)
	}
	g.WriteByte('\n')
}

func (g *generator) writeLines(lines []string) {
	for _, line := range lines {
		g.l(line)
	}
}

func quote(s string) string {
	return strconv.Quote(s)
}

func (g *generator) flagsFile(spec generationSpec) []byte {
	g.writeHeader(flagImports(spec))
	for i, flagType := range spec.types {
		if i > 0 {
			g.l()
		}
		g.writeFlag(spec, flagType, false)
		g.l()
		g.writeFlag(spec, flagType, true)
	}

	return g.Bytes()
}

func (g *generator) writeHeader(imports []string) {
	g.l("// Code generated by flagxgen; DO NOT EDIT.")
	g.l()
	g.l("package flagx")
	if len(imports) > 0 {
		g.l()
		g.writeImports(imports)
	}
}

func (g *generator) writeImports(paths []string) {
	g.l("import (")
	for _, path := range paths {
		g.l(quote(path))
	}
	g.l(")")
}

func codecImports(spec generationSpec) []string {
	imports := make([]string, 0, len(spec.handlers))
	seen := map[string]struct{}{}

	for _, handler := range spec.handlers {
		for _, path := range handler.Imports {
			if _, ok := seen[path]; ok {
				continue
			}
			seen[path] = struct{}{}
			imports = append(imports, path)
		}
	}

	slices.Sort(imports)
	return imports
}

func flagImports(spec generationSpec) []string {
	imports := []string{pflagImportPath}
	seen := map[string]struct{}{
		pflagImportPath: {},
	}

	for _, flagType := range spec.types {
		for _, path := range flagType.Imports {
			if _, ok := seen[path]; ok {
				continue
			}
			seen[path] = struct{}{}
			imports = append(imports, path)
		}
	}

	slices.Sort(imports)
	return imports
}
